version: "3.9"

services:
    anycodemq:
        container_name: 'rabbitmq'
        image: rabbitmq:3.12-management
        restart: always
        environment: 
            - RABBITMQ_DEFAULT_USERNAME=anycodehub
            - RABBITMQ_DEFAULT_PASSWORD=anycodehub
            - RABBITMQ_DEFAULT_VHOST=anycodehub
        ports:
        - 5672:5672
        - 15672:15672 

    anycodehubdb:
        image: postgres
        container_name: 'anycodehubdb'
        restart: always
        environment:
        - POSTGRES_USER=anycodehubdb
        - POSTGRES_PASSWORD=anycodehubdb
        - POSTGRES_DB=anycodehubdb
        ports:
        - 5445:5432
        volumes:
        - E:/MWG:/var/lib/postgresql/data

    anycodehubdb.redis:
        image: redis/redis-stack:latest
        container_name: 'anycodehubdb.redis'
        restart: always
        ports: 
          - 6379:6379
          - 8001:8001

    anycodehubdb.mongodb:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=anycodehubdb
            - MONGO_INITDB_ROOT_PASSWORD=anycodehubdb
        ports:
        - 27017:27017
        volumes:
        - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata: